from __future__ import annotations

import uuid
from dataclasses import dataclass


@dataclass
class SitPayload:
    sit_id: str
    name: str
    description: str | None
    confidence_level: int
    elements: list[dict]


def _escape_xml(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )


def build_rulepack_xml(name: str, sits: list[SitPayload], publisher: str = "SIT Builder") -> tuple[str, str]:
    rulepack_guid = str(uuid.uuid4())

    entity_blocks: list[str] = []
    for sit in sits:
        entity_guid = str(uuid.uuid4())
        primary_patterns = [element for element in sit.elements if element.get("element_role") == "PRIMARY"]
        support_patterns = [element for element in sit.elements if element.get("element_role") == "SUPPORTING"]

        id_match = "\n".join(
            f'<IdMatch idRef="{_escape_xml(element.get("pattern") or "")}" />' for element in primary_patterns if element.get("pattern")
        )
        support_match = "\n".join(
            f'<Match idRef="{_escape_xml(element.get("pattern") or "")}" />' for element in support_patterns if element.get("pattern")
        )

        entity_blocks.append(
            f"""
    <Entity id=\"{entity_guid}\" patternsProximity=\"300\" confidenceLevel=\"{sit.confidence_level}\">
      <Name default=\"true\" langcode=\"en-us\">{_escape_xml(sit.name)}</Name>
      <Pattern confidenceLevel=\"{sit.confidence_level}\">
        <Any minMatches=\"1\">
          {id_match}
          {support_match}
        </Any>
      </Pattern>
    </Entity>
            """.strip()
        )

    rules_body = "\n    ".join(entity_blocks)

    xml = f"""<?xml version=\"1.0\" encoding=\"utf-8\"?>
<RulePackage xmlns=\"http://schemas.microsoft.com/office/2011/mce\" id=\"{rulepack_guid}\" publisher=\"{_escape_xml(publisher)}\" name=\"{_escape_xml(name)}\">
  <LocalizedStrings>
    <Resource id=\"Name\" value=\"{_escape_xml(name)}\" />
  </LocalizedStrings>
  <Rules>
    {rules_body}
  </Rules>
</RulePackage>
"""

    return xml, rulepack_guid


def build_powershell_script(rulepack_file_name: str) -> str:
    return f"""param(
    [Parameter(Mandatory=$true)]
    [string]$RulePackPath = \"{rulepack_file_name}\",
    [PSCredential]$Credential,
    [switch]$WhatIf
)

Connect-IPPSSession -Credential $Credential
$xmlContent = Get-Content $RulePackPath -Raw

if ($WhatIf) {{
    Write-Host \"Would import rulepack: $RulePackPath\"
}} else {{
    New-DlpSensitiveInformationTypeRulePackage -FileData ([System.Text.Encoding]::UTF8.GetBytes($xmlContent))
    Write-Host \"Rulepack imported successfully\"
}}
"""


def build_readme(name: str, purview_guid: str) -> str:
    return f"""# {name} Rulepack

This package was generated by SIT Builder.

- Rulepack GUID: `{purview_guid}`
- Artifacts:
  - `rulepack.xml`
  - `Import-rulepack.ps1`

## Import
1. Open PowerShell with required Purview permissions.
2. Run: `./Import-rulepack.ps1 -RulePackPath ./rulepack.xml -Credential (Get-Credential)`
3. Verify SITs in Microsoft Purview compliance portal.
"""
